name: Check

on:
  push:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Build docs
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install --upgrade mkdocs
        python3 plugindocs.py
        python3 -m mkdocs build
